server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/marketgrid_notification
