server.port=8080

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route mapping to individual microservices (using MVC gateway properties)
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.mvc.routes[1].id=product-service
spring.cloud.gateway.mvc.routes[1].uri=lb://product-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/products/**,/api/v1/categories/**

spring.cloud.gateway.mvc.routes[2].id=vendor-service
spring.cloud.gateway.mvc.routes[2].uri=lb://vendor-service
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/v1/vendors/**

spring.cloud.gateway.mvc.routes[3].id=order-service
spring.cloud.gateway.mvc.routes[3].uri=lb://order-service
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/v1/orders/**,/api/v1/cart/**

spring.cloud.gateway.mvc.routes[4].id=notification-service
spring.cloud.gateway.mvc.routes[4].uri=lb://notification-service
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/v1/notifications/**
